export const agentsList = [
  {
    name: 'Comercializadora Greenhow SA (https://www.greenhow.com.mx)',
    position: '',
    email: '',
    phone: '',
    country: 'MX',
  },
  {
    name: 'MANTTRA-AMERICAS CORP (https://www.manttra-americas.com)',
    position: '',
    email: '',
    phone: '',
    country: 'GT',
  },
  {
    name: 'MANTTRA-AMERICAS CORP (https://www.manttra-americas.com)',
    position: '',
    email: '',
    phone: '',
    country: 'PA',
  },
  {
    name: 'MANTTRA-AMERICAS CORP (https://www.manttra-americas.com)',
    position: '',
    email: '',
    phone: '',
    country: 'EC',
  },
  {
    name: 'Procampo (https://www.procampo.com.pe)',
    position: '',
    email: '',
    phone: '',
    country: 'PE',
  },
  {
    name: 'MANTTRA-AMERICAS CORP (https://www.manttra-americas.com)',
    position: '',
    email: '',
    phone: '',
    country: 'PY',
  },
  {
    name: 'Agroenfoque (https://www.agroenfoque.com.uy)',
    position: '',
    email: '',
    phone: '',
    country: 'UY',
  },
  {
    name: 'Siner (https://www.sinersa.com)',
    position: '',
    email: '',
    phone: '',
    country: 'AR',
  },
  {
    name: 'Lujan Agricola (https://www.lujanagricola.com.ar)',
    position: '',
    email: '',
    phone: '',
    country: 'AR',
  },
  {
    name: 'Agrícola Fermi SRL (Salta, Monte Rico)',
    position: '',
    email: '',
    phone: '',
    country: 'AR',
  },
  {
    name: 'Sustentagro (Oran)',
    position: '',
    email: '',
    phone: '',
    country: 'AR',
  },
  {
    name: 'Surgen SRL (Embarcación)',
    position: '',
    email: '',
    phone: '',
    country: 'AR',
  },
  {
    name: 'Proagro SRL (Tucuman)',
    position: '',
    email: '',
    phone: '',
    country: 'AR',
  },
  {
    name: 'Roberto Chelala (La Banda)',
    position: '',
    email: '',
    phone: '',
    country: 'AR',
  },
  {
    name: 'Multiagro SRL (Obera)',
    position: '',
    email: '',
    phone: '',
    country: 'AR',
  },
  {
    name: 'Agrobiz SRL (Saladas)',
    position: '',
    email: '',
    phone: '',
    country: 'AR',
  },
  {
    name: 'Pablo Dimitri (Concordia, Concordia)',
    position: '',
    email: '',
    phone: '',
    country: 'AR',
  },
  {
    name: 'Fullagro SA (Córdoba)',
    position: '',
    email: '',
    phone: '',
    country: 'AR',
  },
  {
    name: 'Héctor A Bertone SA (Villa María)',
    position: '',
    email: '',
    phone: '',
    country: 'AR',
  },
  {
    name: 'Agrocentral SRL (Mercado Central)',
    position: '',
    email: '',
    phone: '',
    country: 'AR',
  },
  {
    name: 'Nutrientes SA (Pocito)',
    position: '',
    email: '',
    phone: '',
    country: 'AR',
  },
  {
    name: 'Lujan Agricola SA (Lujan de Cuyo)',
    position: '',
    email: '',
    phone: '',
    country: 'AR',
  },
  {
    name: 'Agronomía San Rafael (San Rafael, General Alvear)',
    position: '',
    email: '',
    phone: '',
    country: 'AR',
  },
  {
    name: 'Somaruga Agro SA (Cipolletti)',
    position: '',
    email: '',
    phone: '',
    country: 'AR',
  },
  {
    name: 'Kumei Mapu SRL (General Roca)',
    position: '',
    email: '',
    phone: '',
    country: 'AR',
  },
  {
    name: 'Podlesch SA (Villa Regina)',
    position: '',
    email: '',
    phone: '',
    country: 'AR',
  },
];

export const regionManagers = [
  {
    name: 'Lenin Guerrero Ch.',
    position: 'Zonal Técnico Comercial Norte',
    email: 'Ingeniero Agrónomo',
    phone: '',
    country: 'PE',
  },
  {
    name: 'José Luis Assereto A',
    position: 'Zonal Técnico Comercial Ica',
    email: 'Ingeniero Agrónomo',
    phone: '',
    country: 'PE',
  },
  {
    name: 'Rolando Silva',
    position: 'Country Manager Perú Bolivia',
    email: '',
    phone: '',
    country: 'PE',
  },
  {
    name: 'Rolando Silva',
    position: 'Country Manager Perú Bolivia',
    email: '',
    phone: '',
    country: 'BO',
  },
  {
    name: 'Emiliano Castilla',
    position: 'Asistente Técnico Comercial',
    email: 'ingeniero Agrónomo',
    phone: '',
    country: 'AR',
  },

  {
    name: 'Jorge Schell',
    position: 'Country Manager Mercosur',
    email: '',
    phone: '',
    country: 'AR',
  },
  {
    name: 'Jorge Schell',
    position: 'Country Manager Mercosur',
    email: '',
    phone: '',
    country: 'UY',
  },
  {
    name: 'Click para más información',
    position: '',
    email: '',
    phone: '',
    country: 'CL',
  },
];

export const chileanManagers = [
  {
    name: 'Rolando Silva H',
    position: 'Agente Zonal',
    email: 'rsilva@aminochem.cl',
    phone: '+56 9 94427692',
    region: 'CL-AP',
  },
  {
    name: 'Rolando Silva H',
    position: 'Agente Zonal',
    email: 'rsilva@aminochem.cl',
    phone: '+56 9 94427692',
    region: 'CL-TA',
  },
  {
    name: 'Rolando Silva H',
    position: 'Agente Zonal',
    email: 'rsilva@aminochem.cl',
    phone: '+56 9 94427692',
    region: 'CL-AN',
  },
  {
    name: 'Rolando Silva H',
    position: 'Agente Zonal',
    email: 'rsilva@aminochem.cl',
    phone: '+56 9 94427692',
    region: 'CL-AT',
  },
  {
    name: 'Rolando Silva H',
    position: 'Agente Zonal',
    email: 'rsilva@aminochem.cl',
    phone: '+56 9 94427692',
    region: 'CL-CO',
  },
  {
    name: 'Francisco Ascui',
    position: 'Gerente General',
    email: 'francisco.ascui@aminochem.cl',
    phone: '+56 9 87282496',
    region: 'CL-VS',
  },
  {
    name: 'Francisco Ascui',
    position: 'Gerente General',
    email: 'francisco.ascui@aminochem.cl',
    phone: '+56 9 87282496',
    region: 'CL-RM',
  },
  {
    name: 'Juan Pablo Vergara',
    position: 'Agente Zonal',
    email: 'jvergara@aminochem.cl',
    phone: '+56 9 68310700',
    region: 'CL-LI',
  },
  {
    name: 'Javiera Munita',
    position: 'Agente Zonal',
    email: 'jmunita@aminochem.cl',
    phone: '',
    region: 'CL-ML',
  },
  {
    name: 'Manuel Contreras C.',
    position: 'Agente Zonal',
    email: 'mcontreras@aminochem.cl',
    phone: '+56 9 42633293',
    region: 'CL-BI',
  },
  {
    name: 'Carlos Baier A.',
    position: 'Agente Zonal Sur',
    email: 'cbaier@aminochem.cl',
    phone: '+56 9 96379251',
    region: 'CL-AR',
  },
  {
    name: 'Carlos Baier A.',
    position: 'Agente Zonal Sur',
    email: 'cbaier@aminochem.cl',
    phone: '+56 9 96379251',
    region: 'CL-LR',
  },
  {
    name: 'Carlos Baier A.',
    position: 'Agente Zonal Sur',
    email: 'cbaier@aminochem.cl',
    phone: '+56 9 96379251',
    region: 'CL-LL',
  },
];

export const regionAgentsList = [
  {
    name: 'Agropiamonte S.A.',
    position: '',
    email: 'http://agropiemonte.cl/',
    phone: '',
    region: 'CL-AP',
  },
  {
    name: 'Norchimet Ltda.',
    position: '',
    email: '',
    phone: '',
    region: 'CL-AP',
  },
  {
    name: 'Agrocomercial Norte Blanco',
    position: '',
    email: '',
    phone: '',
    region: 'CL-AP',
  },
  {
    name: 'Comercial Mi Bodega',
    position: '',
    email: '',
    phone: '',
    region: 'CL-AP',
  },
  {
    name: 'Agrícola del Norte',
    position: '',
    email: '',
    phone: '',
    region: 'CL-AP',
  },
  {
    name: 'Bodega Adela',
    position: '',
    email: '',
    phone: '',
    region: 'CL-AP',
  },
  {
    name: 'Insumos Framacop',
    position: '',
    email: '',
    phone: '',
    region: 'CL-AP',
  },
  {
    name: 'Insumos María Angélica',
    position: '',
    email: '',
    phone: '',
    region: 'CL-AP',
  },
  {
    name: 'Copeval SA',
    position: '',
    email: 'http://copeval.cl',
    phone: '',
    region: 'CL-AT',
  },
  {
    name: 'Copeval SA',
    position: '',
    email: 'http://copeval.cl',
    phone: '',
    region: 'CL-CO',
  },
  {
    name: 'Cals Ltda',
    position: '',
    email: 'http://cals.cl',
    phone: '',
    region: 'CL-CO',
  },
  {
    name: 'Copeval SA',
    position: '',
    email: 'http://copeval.cl',
    phone: '',
    region: 'CL-VS',
  },
  {
    name: 'Cals Ltda',
    position: '',
    email: 'http://cals.cl',
    phone: '',
    region: 'CL-VS',
  },
  {
    name: 'Coagra SA',
    position: '',
    email: 'http://coagra.cl',
    phone: '',
    region: 'CL-VS',
  },
  {
    name: 'Cals Ltda',
    position: '',
    email: 'http://cals.cl',
    phone: '',
    region: 'CL-RM',
  },
  {
    name: 'Copeval SA',
    position: '',
    email: 'http://copeval.cl',
    phone: '',
    region: 'CL-RM',
  },
  {
    name: 'Agrícola Padre Hurtado',
    position: '',
    email: 'http://agricolapadrehurtado.cl',
    phone: '',
    region: 'CL-RM',
  },
  {
    name: 'Coagra SA',
    position: '',
    email: 'http://coagra.cl',
    phone: '',
    region: 'CL-RM',
  },
  {
    name: 'Coagra SA',
    position: '',
    email: 'http://coagra.cl',
    phone: '',
    region: 'CL-LI',
  },
  {
    name: 'Cals Ltda',
    position: '',
    email: 'http://cals.cl',
    phone: '',
    region: 'CL-LI',
  },
  {
    name: 'Copeval SA',
    position: '',
    email: 'http://copeval.cl',
    phone: '',
    region: 'CL-LI',
  },
  {
    name: 'Coagra SA',
    position: '',
    email: 'http://coagra.cl',
    phone: '',
    region: 'CL-ML',
  },
  {
    name: 'Cals Ltda',
    position: '',
    email: 'http://cals.cl',
    phone: '',
    region: 'CL-ML',
  },
  {
    name: 'Copeval SA',
    position: '',
    email: 'http://copeval.cl',
    phone: '',
    region: 'CL-ML',
  },
  {
    name: 'Coagra SA',
    position: '',
    email: 'http://coagra.cl',
    phone: '',
    region: 'CL-BI',
  },
  {
    name: 'Cals Ltda',
    position: '',
    email: 'http://cals.cl',
    phone: '',
    region: 'CL-BI',
  },
  {
    name: 'Copeval SA',
    position: '',
    email: 'http://copeval.cl',
    phone: '',
    region: 'CL-BI',
  },
  {
    name: 'Cooprinsem',
    position: '',
    email: 'http://cooprinsem.cl',
    phone: '',
    region: 'CL-BI',
  },
  {
    name: 'Coagra SA',
    position: '',
    email: 'http://coagra.cl',
    phone: '',
    region: 'CL-AR',
  },
  {
    name: 'Agrícola Lobert Ltda',
    position: '',
    email: 'http://lobert.cl',
    phone: '',
    region: 'CL-AR',
  },
  {
    name: 'Copeval SA',
    position: '',
    email: 'http://copeval.cl',
    phone: '',
    region: 'CL-AR',
  },
  {
    name: 'Cooprinsem',
    position: '',
    email: 'http://cooprinsem.cl',
    phone: '',
    region: 'CL-AR',
  },
  {
    name: 'Copeval SA',
    position: '',
    email: 'http://copeval.cl',
    phone: '',
    region: 'CL-LR',
  },
  {
    name: 'Cooprinsem',
    position: '',
    email: 'http://cooprinsem.cl',
    phone: '',
    region: 'CL-LR',
  },
  {
    name: 'Coagra SA',
    position: '',
    email: 'http://coagra.cl',
    phone: '',
    region: 'CL-LL',
  },
  {
    name: 'Copeval SA',
    position: '',
    email: 'http://copeval.cl',
    phone: '',
    region: 'CL-LL',
  },
  {
    name: 'Cooprinsem',
    position: '',
    email: 'http://cooprinsem.cl',
    phone: '',
    region: 'CL-LL',
  },
];
