export const agentsList = [
  {
    name: 'Rolando Silva H.',
    position: 'Country Manager Perú-Bolivia',
    email: 'rsilva@aminochem.cl',
    phone: '+51 9 50431988',
    country: 'PE',
  },
  {
    name: 'Rolando Silva H.',
    position: 'Country Manager Perú-Bolivia',
    email: 'rsilva@aminochem.cl',
    phone: '+51 9 50431988',
    country: 'BO',
  },
  {
    name: 'Jorge Schell',
    position: 'Country Manager Mercosur',
    email: 'jschell@aminochem.cl',
    phone: '+54 9 11 51690347',
    country: 'UY',
  },
  {
    name: 'Jorge Schell',
    position: 'Country Manager Mercosur',
    email: 'jschell@aminochem.cl',
    phone: '+54 9 11 51690347',
    country: 'AR',
  },
  {
    name: 'Click para más información',
    position: '',
    email: '',
    phone: '',
    country: 'CL',
  },
];

export const regionAgentsList = [
  {
    name: 'Agropiamonte S.A. (www.agropiemonte.cl/)',
    position: '',
    email: '',
    phone: '',
    region: 'CL-AP',
  },
  {
    name: 'Norchimet Ltda.',
    position: '',
    email: '',
    phone: '',
    region: 'CL-AP',
  },
  {
    name: 'Agrocomercial Norte Blanco',
    position: '',
    email: '',
    phone: '',
    region: 'CL-AP',
  },
  {
    name: 'Comercial Mi Bodega',
    position: '',
    email: '',
    phone: '',
    region: 'CL-AP',
  },
  {
    name: 'Agrícola del Norte',
    position: '',
    email: '',
    phone: '',
    region: 'CL-AP',
  },
  {
    name: 'Bodega Adela',
    position: '',
    email: '',
    phone: '',
    region: 'CL-AP',
  },
  {
    name: 'Insumos Framacop',
    position: '',
    email: '',
    phone: '',
    region: 'CL-AP',
  },
  {
    name: 'Insumos María Angélica',
    position: '',
    email: '',
    phone: '',
    region: 'CL-AP',
  },
  {
    name: 'Copeval SA  (www.copeval.cl)',
    position: '',
    email: '',
    phone: '',
    region: 'CL-AT',
  },
  {
    name: 'Copeval SA  (www.copeval.cl)',
    position: '',
    email: '',
    phone: '',
    region: 'CL-CO',
  },
  {
    name: 'Cals Ltda (www.cals.cl)',
    position: '',
    email: '',
    phone: '',
    region: 'CL-CO',
  },
  {
    name: 'Copeval SA  (www.copeval.cl)',
    position: '',
    email: '',
    phone: '',
    region: 'CL-VS',
  },
  {
    name: 'Cals Ltda (www.cals.cl)',
    position: '',
    email: '',
    phone: '',
    region: 'CL-VS',
  },
  {
    name: 'Coagra SA (www.coagra.cl)',
    position: '',
    email: '',
    phone: '',
    region: 'CL-VS',
  },
  {
    name: 'Cals Ltda (www.cals.cl)',
    position: '',
    email: '',
    phone: '',
    region: 'CL-RM',
  },
  {
    name: 'Copeval SA  (www.copeval.cl)',
    position: '',
    email: '',
    phone: '',
    region: 'CL-RM',
  },
  {
    name: 'Agrícola Padre Hurtado (www.agricolapadrehurtado.cl)',
    position: '',
    email: '',
    phone: '',
    region: 'CL-RM',
  },
  {
    name: 'Coagra SA (www.coagra.cl)',
    position: '',
    email: '',
    phone: '',
    region: 'CL-RM',
  },
  {
    name: 'Coagra SA (www.coagra.cl)',
    position: '',
    email: '',
    phone: '',
    region: 'CL-LI',
  },
  {
    name: 'Cals Ltda (www.cals.cl)',
    position: '',
    email: '',
    phone: '',
    region: 'CL-LI',
  },
  {
    name: 'Copeval SA  (www.copeval.cl)',
    position: '',
    email: '',
    phone: '',
    region: 'CL-LI',
  },
  {
    name: 'Coagra SA (www.coagra.cl)',
    position: '',
    email: '',
    phone: '',
    region: 'CL-ML',
  },
  {
    name: 'Cals Ltda (www.cals.cl)',
    position: '',
    email: '',
    phone: '',
    region: 'CL-ML',
  },
  {
    name: 'Copeval SA  (www.copeval.cl)',
    position: '',
    email: '',
    phone: '',
    region: 'CL-ML',
  },
  {
    name: 'Coagra SA (www.coagra.cl)',
    position: '',
    email: '',
    phone: '',
    region: 'CL-BI',
  },
  {
    name: 'Cals Ltda (www.cals.cl)',
    position: '',
    email: '',
    phone: '',
    region: 'CL-BI',
  },
  {
    name: 'Copeval SA  (www.copeval.cl)',
    position: '',
    email: '',
    phone: '',
    region: 'CL-BI',
  },
  {
    name: 'Cooprinsem (www.cooprinsem.cl)',
    position: '',
    email: '',
    phone: '',
    region: 'CL-BI',
  },
  {
    name: 'Coagra SA (www.coagra.cl)',
    position: '',
    email: '',
    phone: '',
    region: 'CL-AR',
  },
  {
    name: 'Agrícola Lobert Ltda  (www.lobert.cl)',
    position: '',
    email: '',
    phone: '',
    region: 'CL-AR',
  },
  {
    name: 'Copeval SA  (www.copeval.cl)',
    position: '',
    email: '',
    phone: '',
    region: 'CL-AR',
  },
  {
    name: 'Cooprinsem (www.cooprinsem.cl)',
    position: '',
    email: '',
    phone: '',
    region: 'CL-AR',
  },
  {
    name: 'Copeval SA  (www.copeval.cl)',
    position: '',
    email: '',
    phone: '',
    region: 'CL-LR',
  },
  {
    name: 'Cooprinsem (www.cooprinsem.cl)',
    position: '',
    email: '',
    phone: '',
    region: 'CL-LR',
  },
  {
    name: 'Coagra SA (www.coagra.cl)',
    position: '',
    email: '',
    phone: '',
    region: 'CL-LL',
  },
  {
    name: 'Copeval SA  (www.copeval.cl)',
    position: '',
    email: '',
    phone: '',
    region: 'CL-LL',
  },
  {
    name: 'Cooprinsem (www.cooprinsem.cl)',
    position: '',
    email: '',
    phone: '',
    region: 'CL-LL',
  },
];
